[tool.black]
line-length = 88
target-version = ['py36']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | _build
    | build
    | dist
    | docs
    | bluez
  )/
)
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
skip_glob = [".local/*", ".venv/*", "doc/*"]
known_first_party = ["bluetooth_mesh"]
default_section = "THIRDPARTY"
